services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env.dev
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    container_name: django-web
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend/inventario-ecoladrillos  # <- Ruta donde está tu frontend con el Dockerfile
      dockerfile: Dockerfile
    ports:
      - 3000:80  # React servirá en el puerto 80 dentro del contenedor, pero tú lo expones en 3000
    depends_on:
      - web
