# Generated by Django 5.2.4 on 2025-08-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('operario', 'Operario'), ('administrador', 'Administrador')], help_text='Tipo de usuario: operario o administrador', max_length=20),
        ),
    ]
