# Generated by Django 5.2.4 on 2025-08-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('stock_fecha', 'Stock en Fecha'), ('resumen_inventario', 'Resumen de Inventario'), ('resumen_retiros', 'Resumen de Retiros')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos_reporte', models.JSONField()),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.operario')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Ecoladrillo',
            fields=[
                ('id_ecoladrillo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('cantidad_material_requerida', models.IntegerField(default=1)),
                ('cantidad', models.IntegerField(default=0)),
                ('material_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoladrillos', to='Inventario.material')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEcoladrillo',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('ecoladrillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.ecoladrillo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMaterial',
            fields=[
                ('id_registro_material', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('origen', models.CharField(default='', max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.material')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteResumenInventario',
            fields=[
                ('reporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventario.reporte')),
            ],
            bases=('Inventario.reporte',),
        ),
        migrations.CreateModel(
            name='ReporteResumenRetiros',
            fields=[
                ('reporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventario.reporte')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            bases=('Inventario.reporte',),
        ),
        migrations.CreateModel(
            name='ReporteStockFecha',
            fields=[
                ('reporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventario.reporte')),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
            ],
            bases=('Inventario.reporte',),
        ),
        migrations.CreateModel(
            name='RetiroEcoladrillo',
            fields=[
                ('id_retiro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('motivo', models.CharField(max_length=200)),
                ('ecoladrillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.ecoladrillo')),
            ],
        ),
    ]
