# Generated by Django 5.2.4 on 2025-08-01 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMaterial',
            fields=[
                ('id_registro_material', models.AutoField(primary_key=True, serialize=False)),
                ('id_ingreso', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('origen', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RetiroEcoladrillo',
            fields=[
                ('id_retiro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('motivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ecoladrillo',
            fields=[
                ('id_ecoladrillo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('cantidad_material_requerida', models.IntegerField(default=1)),
                ('cantidad', models.IntegerField(default=0)),
                ('material_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoladrillos', to='Inventario.material')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEcoladrillo',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('ecoladrillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.ecoladrillo')),
            ],
        ),
    ]
