# Generated by Django 4.1.3 on 2025-07-28 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ecoladrillo',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('id_ecoladrillo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_insumo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RetiroEcoladrillo',
            fields=[
                ('id_retiro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('motivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMaterial',
            fields=[
                ('id_registro_material', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ingreso', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('origen', models.CharField(default='', max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.material')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEcoladrillo',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('material_usado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.material')),
            ],
        ),
    ]
