# Generated by Django 5.2.4 on 2025-08-01 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroecoladrillo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que registró la producción', on_delete=django.db.models.deletion.CASCADE, related_name='registros_ecoladrillos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registromaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.material'),
        ),
        migrations.AddField(
            model_name='registromaterial',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que registró el material', on_delete=django.db.models.deletion.CASCADE, related_name='registros_materiales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retiroecoladrillo',
            name='ecoladrillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.ecoladrillo'),
        ),
        migrations.AddField(
            model_name='retiroecoladrillo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realizó el retiro', on_delete=django.db.models.deletion.CASCADE, related_name='retiros_ecoladrillos', to=settings.AUTH_USER_MODEL),
        ),
    ]
