# Generated by Django 5.2.4 on 2025-08-03 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_remove_registromaterial_id_ingreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_generacion']},
        ),
        migrations.AddField(
            model_name='reporte',
            name='datos_reporte',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.operario'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_reporte',
            field=models.CharField(choices=[('stock_fecha', 'Stock en Fecha'), ('resumen_inventario', 'Resumen de Inventario'), ('resumen_retiros', 'Resumen de Retiros')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
