# Generated by Django 5.2.4 on 2025-07-29 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_administrador_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroecoladrillo',
            name='cantidad_por_material',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroecoladrillo',
            name='ecoladrillo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.ecoladrillo'),
        ),
    ]
