# Generated by Django 5.2.4 on 2025-08-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_reporte_options_reporte_datos_reporte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_inicio',
        ),
    ]
