# Generated by Django 5.2.4 on 2025-07-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_registroecoladrillo_cantidad_por_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroecoladrillo',
            name='cantidad_por_material',
        ),
        migrations.AddField(
            model_name='material',
            name='cantidad_para_ecoladrillo',
            field=models.IntegerField(default=0),
        ),
    ]
