# Generated by Django 5.2.4 on 2025-07-31 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_remove_registroecoladrillo_cantidad_por_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiroecoladrillo',
            name='ecoladrillo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.ecoladrillo'),
            preserve_default=False,
        ),
    ]
