# Generated by Django 5.2.4 on 2025-08-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_remove_reporte_fecha_fin_remove_reporte_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
