# Generated by Django 5.2.4 on 2025-07-31 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_retiroecoladrillo_ecoladrillo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cantidad_para_ecoladrillo',
        ),
        migrations.RemoveField(
            model_name='registroecoladrillo',
            name='material_usado',
        ),
        migrations.AddField(
            model_name='ecoladrillo',
            name='cantidad_material_requerida',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ecoladrillo',
            name='material_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ecoladrillos', to='Inventario.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecoladrillo',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroecoladrillo',
            name='ecoladrillo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.ecoladrillo'),
            preserve_default=False,
        ),
    ]
