# Generated by Django 5.2.4 on 2025-07-31 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_remove_material_cantidad_para_ecoladrillo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Operario',
        ),
        migrations.AddField(
            model_name='registroecoladrillo',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuario que registró la producción', on_delete=django.db.models.deletion.CASCADE, related_name='registros_ecoladrillos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registromaterial',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuario que registró el material', on_delete=django.db.models.deletion.CASCADE, related_name='registros_materiales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retiroecoladrillo',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuario que realizó el retiro', on_delete=django.db.models.deletion.CASCADE, related_name='retiros_ecoladrillos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
